# Generated by Django 4.1.1 on 2024-04-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to='images/'),
        ),
    ]
