# Generated by Django 4.1.1 on 2024-05-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_eventrequest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('academic_level', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('Place_of_birth', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
